import Tests.AccessSdkSpec
import Tests.BuildSpec
import Tests.CFGSpec
import Tests.CappedSpec
import Tests.CliSpec
import Tests.ConstSpec
import Tests.CoreCodecSpec
import Tests.CoreCollectionsSpec
import Tests.CoreMathSpec
import Tests.CounterSpec
import Tests.CreditsSpec
import Tests.EvmBitmapSpec
import Tests.EvmBoundedSpec
import Tests.EvmBuildSpec
import Tests.EvmCallResultSpec
import Tests.EvmCtxSpec
import Tests.EvmEffectStateSpec
import Tests.EvmEnvironmentSpec
import Tests.EvmErc1155Spec
import Tests.EvmErc721Spec
import Tests.EvmExceptErgonomicsSpec
import Tests.EvmLogErrorSpec
import Tests.EvmOrderedStorageSpec
import Tests.EvmPausableSpec
import Tests.EvmPayableSpec
import Tests.EvmPrecompileSpec
import Tests.EvmReentrancySpec
import Tests.EvmRolesSpec
import Tests.EvmSafeCastSpec
import Tests.EvmSdkSpec
import Tests.EvmSearchSpec
import Tests.EvmSpec
import Tests.EvmStaticStorageSpec
import Tests.EvmStorageCheckpointsSpec
import Tests.EvmStorageEnumerableMapSpec
import Tests.EvmStorageEnumerableSetSpec
import Tests.EvmStorageRingSpec
import Tests.EvmStorageVecSpec
import Tests.EvmTokenErgonomicsSpec
import Tests.EvmTypedErrorSpec
import Tests.Fixtures
import Tests.FlagSpec
import Tests.LangSpec
import Tests.LayoutSpec
import Tests.OwnableSpec
import Tests.PairSpec
import Tests.PhaseSpec
import Tests.ProfileSpec
import Tests.ProofSpec
import Tests.Sha256Spec
import Tests.TargetOpsSpec
import Tests.TipJarSpec
import Tests.TokenSpec
import Tests.TwoStepCounterSpec
import Tests.TokenShapeSpec
import Tests.Erc20MetaSpec
import Tests.VaultSpec
import Tests.WideSpec
import Tests.WindowSpec
